version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - "4000:4000" # Mapear puerto del backend
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network # Asocia el backend a la red personalizada

  frontend:
    build:
      context: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80" # Mapear puerto del frontend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network # Asocia el backend a la red personalizada


networks:
  app-network:
    driver: bridge